/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia_se_deteccion_minerales;

import javax.swing.JOptionPane;
import net.sf.clipsrules.jni.Environment;
import net.sf.clipsrules.jni.FactAddressValue;
import net.sf.clipsrules.jni.LexemeValue;
import net.sf.clipsrules.jni.MultifieldValue;

/**
 *
 * @author Sebastian
 */
public class Sistema_Experto extends javax.swing.JFrame {

    /**
     * Creates new form Sistema_Experto
     */
    Environment clips;
    
    public Sistema_Experto() {
        initComponents();
        clips=new Environment();
        clips.load("src/CLIPS/proyectoIA.CLP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("SISTEMA EXPERTO - DETECCIÓN DE MINERALES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Raya:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setText("Color:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel4.setText("Transparencia:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setText("Factura:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel6.setText("Hábito:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setText("Dureza:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setText("Luminiscencia:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel9.setText("Brillo:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel11.setText("Magnetismo:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuerte", "Sin Magnetismo", "Despues de Calentar" }));
        jPanel3.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 190, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incoloro", "Blanco", "Rosado", "Amarillo", "Marron", "Gris Blanco", "Beige", "Amarillo Verdoso", "Gris", "Gris Verdoso", "Verde Azulado", "Morado", "Blanco Plata", "Blanco Verdoso", "Marron Verdoso", "Verde", "Marron Claro", "Marron Oscuro", "Negro", "Rojo", "Azul", "Amarillo Laton", "Celeste", "Azul Oscuro", "Negro Verdoso", "Negro Grisaceo", "Azul Celeste", "Celeste", "Verde Oliva", "Ocre", "Rojo Ladrillo", "Marron Verdoso", "Verde Azulado", "Verde Amarillento", "Pardo", "Blanco Rojizo", "Blanco Verdoso", "Blanco Amarillento", "Gris Amarillento", "Rojo Rosaceo", "Verde Manzana" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 190, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opaco", "Translucido", "Sub Translucido", "Transparente" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fragil", "Astillosa", "Concoidal", "Irregular", "Sub Concoidal", "Sectil", "Terrosa" }));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, -1));

        jTextField1.setText("1");
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 70, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acicular", "Columnar", "Cristalino", "Fibroso", "Granular", "Masivo", "Foliado", "Botroidal", "Laminar", "Estriado", "Terroso", "Diseminado", "Estalactita", "En Bloque", "Micaceo" }));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 190, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ligeramente Fluorescente", "Fluorescente", "No Fluorescente", "Fosforescente", "Tribuluminiscente" }));
        jPanel3.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 190, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanca", "Gris Verdoso", "Negra Verduzca", "Negro Grisaceo", "Verde Manzana", "Celeste", "Gris", "Blanco Marron", "Verde", "Marron Claro", "Verde Claro" }));
        jPanel3.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 190, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metalico", "Vitreo", "Diamantino", "Resinoso", "Perlado", "Mate", "Iridiscente", "Terroso", "Graso" }));
        jPanel3.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 190, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minerales-cobre.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 890, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clips.reset();
        if(validar()){
            String color = procesar((String) jComboBox1.getSelectedItem());
            String transparencia = procesar((String) jComboBox2.getSelectedItem());
            String fractura = procesar((String) jComboBox3.getSelectedItem());
            String habito = procesar((String) jComboBox4.getSelectedItem());
            String dureza = jTextField1.getText();
            String luminiscencia = procesar((String) jComboBox5.getSelectedItem());
            String brillo = procesar((String) jComboBox6.getSelectedItem());
            String magnetismo = procesar((String) jComboBox7.getSelectedItem());
            String raya = procesar((String) jComboBox8.getSelectedItem());
            String hecho = "(Mineral (Color "+color+")(Transparencia "+transparencia+")(Fractura "+fractura+")(Habito "+habito+")(Dureza "+dureza+")"
            + "(Luminiscencia "+luminiscencia+")(Brillo "+brillo+")(Magnetismo "+magnetismo+")(Raya "+raya+"))";

            clips.eval("(assert "+hecho+")");
            clips.run();
            try{
                MultifieldValue mv = (MultifieldValue) clips.eval("(find-all-facts ((?f Mineral)) TRUE)");
                FactAddressValue fact = (FactAddressValue) mv.multifieldValue().get(0);
                try {
                    String nombre = ((LexemeValue) fact.getFactSlot("Nombre")).lexemeValue().toUpperCase();
                    if (nombre.equals("")){
                        String messageStr = "<html>" + "HE FALLADO COMO SISTEMA EXPERTO" + "<br>" + ", AQUELLO POR LO QUE EL HUMANO ME HA CREADO" + "<br><br>" + "PEDIR AL INGENIERO DE CONOCIMIENTO INGRESAR MÁS REGLAS." +
                        "<br><br>" + "DISCULPE LA INCOVENENCIA, INTENTAR IDENTIFICAR OTRO MINERAL";
                        JOptionPane.showMessageDialog(this, messageStr, "NO TENGO LA SUFICIENTE PERICIA", JOptionPane.ERROR_MESSAGE);
                    }
                    else{
                        String messageStr = "<html>" + "EL MINERAL ES: " + nombre + "<br>";
                        JOptionPane.showMessageDialog(this, messageStr, "IDENTIFICACIÓN DE MINERAL", JOptionPane.INFORMATION_MESSAGE);
                    }
                } catch (Exception ex) {
                    System.out.println("ERROR");
                }
            }catch (Exception ex) {
                System.out.println("VALUES FOR SLOTS NOT VALID");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Dureza incorecta", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String procesar(String cadena){
        return '"'+cadena+'"';
    }
    
    private boolean validar(){
        try{
            String cad=jTextField1.getText();
            double num=Double.parseDouble(cad);
            if(1<=num && num<=10){
                return true;
            }
        }catch(NumberFormatException e){
            return false;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
